// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3GnZzON5N6DVAlg3GCBW-GcVJ9BoSrDc',
    appId: '1:996272508120:web:00b947c5a5191da44d9bad',
    messagingSenderId: '996272508120',
    projectId: 'medicalclinic-9c2a6',
    authDomain: 'medicalclinic-9c2a6.firebaseapp.com',
    databaseURL: 'https://medicalclinic-9c2a6-default-rtdb.firebaseio.com',
    storageBucket: 'medicalclinic-9c2a6.appspot.com',
    measurementId: 'G-MP08Z5M4WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBTiP1ouDZ6VTJsBWd0vFEangIOix_tZg',
    appId: '1:996272508120:android:6e9d8bcd1fa227344d9bad',
    messagingSenderId: '996272508120',
    projectId: 'medicalclinic-9c2a6',
    databaseURL: 'https://medicalclinic-9c2a6-default-rtdb.firebaseio.com',
    storageBucket: 'medicalclinic-9c2a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBkoaexB5_S6-6sPdlc1VzDDlZxedw3YI',
    appId: '1:996272508120:ios:b7f580271ae88c314d9bad',
    messagingSenderId: '996272508120',
    projectId: 'medicalclinic-9c2a6',
    databaseURL: 'https://medicalclinic-9c2a6-default-rtdb.firebaseio.com',
    storageBucket: 'medicalclinic-9c2a6.appspot.com',
    iosBundleId: 'com.example.proyectoGraduacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBkoaexB5_S6-6sPdlc1VzDDlZxedw3YI',
    appId: '1:996272508120:ios:b7f580271ae88c314d9bad',
    messagingSenderId: '996272508120',
    projectId: 'medicalclinic-9c2a6',
    databaseURL: 'https://medicalclinic-9c2a6-default-rtdb.firebaseio.com',
    storageBucket: 'medicalclinic-9c2a6.appspot.com',
    iosBundleId: 'com.example.proyectoGraduacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3GnZzON5N6DVAlg3GCBW-GcVJ9BoSrDc',
    appId: '1:996272508120:web:354b6e385b3d2fdc4d9bad',
    messagingSenderId: '996272508120',
    projectId: 'medicalclinic-9c2a6',
    authDomain: 'medicalclinic-9c2a6.firebaseapp.com',
    databaseURL: 'https://medicalclinic-9c2a6-default-rtdb.firebaseio.com',
    storageBucket: 'medicalclinic-9c2a6.appspot.com',
    measurementId: 'G-FKR748NJ1P',
  );
}
